In [54]:
import numpy as np
import torch
from torch import nn

### Part 1:

#### Task 1.1:

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(f"Tensor từ list:\n {x_data}")

Tensor từ list:
 tensor([[1, 2],
        [3, 4]])


In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(f"Tensor từ NumPy array:\n {x_np}")

Tensor từ NumPy array:
 tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [4]:
x_ones = torch.ones_like(x_data) # tạo tensor gồm các số 1 có cùng shape với x_data
print(f"Ones Tensor:\n {x_ones}")

Ones Tensor:
 tensor([[1, 1],
        [1, 1]])


In [5]:
x_rand = torch.rand_like(x_data, dtype=torch.float) # tạo tensor ngẫu nhiên
print(f"Random Tensor:\n {x_rand}\n")

Random Tensor:
 tensor([[0.7307, 0.4925],
        [0.6624, 0.1312]])



In [6]:
print(f"Shape của tensor: {x_rand.shape}")
print(f"Datatype của tensor: {x_rand.dtype}")
print(f"Device lưu trữ tensor: {x_rand.device}")

Shape của tensor: torch.Size([2, 2])
Datatype của tensor: torch.float32
Device lưu trữ tensor: cpu


#### Task 1.2:

In [7]:
x_data + x_data

tensor([[2, 4],
        [6, 8]])

In [8]:
x_data * 5

tensor([[ 5, 10],
        [15, 20]])

In [9]:
x_data * x_data

tensor([[ 1,  4],
        [ 9, 16]])

In [10]:
x_data @ x_data.T

tensor([[ 5, 11],
        [11, 25]])

#### Task 1.3:

In [11]:
x_data[0]

tensor([1, 2])

In [12]:
x_data[:, 1]

tensor([2, 4])

In [13]:
x_data[1, 1]

tensor(4)

#### Task 1.4:

In [15]:
test = torch.rand(size=(4, 4), dtype=torch.float)

In [20]:
test.view(size=(16,1))

tensor([[0.3118],
        [0.3983],
        [0.0853],
        [0.7884],
        [0.6630],
        [0.6229],
        [0.5483],
        [0.7870],
        [0.5790],
        [0.8707],
        [0.6906],
        [0.0078],
        [0.4749],
        [0.7756],
        [0.8232],
        [0.9322]])

In [21]:
test.reshape(16, 1)

tensor([[0.3118],
        [0.3983],
        [0.0853],
        [0.7884],
        [0.6630],
        [0.6229],
        [0.5483],
        [0.7870],
        [0.5790],
        [0.8707],
        [0.6906],
        [0.0078],
        [0.4749],
        [0.7756],
        [0.8232],
        [0.9322]])

### Part 2:

#### Task 2.1:

In [45]:
x = torch.ones(1, requires_grad=True)
print(f"x: {x}")

x: tensor([1.], requires_grad=True)


In [47]:
y = x + 2
print(f"y: {y}")

y: tensor([3.], grad_fn=<AddBackward0>)


In [24]:
print(f"grad_fn của y: {y.grad_fn}")

grad_fn của y: <AddBackward0 object at 0x0000012C24CD92A0>


In [48]:
z = y * y * 3

# Tính đạo hàm của z theo x
z.backward() # tương đương z.backward(torch.tensor(1.))

# Đạo hàm được lưu trong thuộc tính .grad
# Ta có z = 3 * (x+2)^2 => dz/dx = 6 * (x+2). Với x=1, dz/dx = 18
print(f"Đạo hàm của z theo x: {x.grad}")

Đạo hàm của z theo x: tensor([18.])


### Part  3:

#### Task 3.1:

In [52]:
linear_layer = torch.nn.Linear(in_features=5, out_features=2)
input_tensor = torch.randn(3, 5) # 3 mẫu, mỗi mẫu 5 chiều
output = linear_layer(input_tensor)

print(f"Input shape: {input_tensor.shape}")
print(f"Output shape: {output.shape}")
print(f"Output:\n {output}")

Input shape: torch.Size([3, 5])
Output shape: torch.Size([3, 2])
Output:
 tensor([[9.0404e-04, 1.6796e+00],
        [2.8094e-01, 7.7699e-01],
        [3.5547e-01, 9.1645e-03]], grad_fn=<AddmmBackward0>)


#### Task 3.2:

In [53]:
embedding_layer = torch.nn.Embedding(num_embeddings=10, embedding_dim=3)
input_indices = torch.LongTensor([1, 5, 0, 8])
embeddings = embedding_layer(input_indices)

print(f"Input shape: {input_indices.shape}")
print(f"Output shape: {embeddings.shape}")
print(f"Embeddings:\n {embeddings}")

Input shape: torch.Size([4])
Output shape: torch.Size([4, 3])
Embeddings:
 tensor([[-0.9322, -1.5683, -1.1515],
        [ 0.2198, -0.3848,  1.5264],
        [-0.8992, -0.9747, -1.1643],
        [ 0.1930, -1.7837, -0.5032]], grad_fn=<EmbeddingBackward0>)


#### Task 3.3:

In [55]:
class MyFirstModel(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, output_dim):
        super(MyFirstModel, self).__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.linear = nn.Linear(embedding_dim, hidden_dim)
        self.activation = nn.ReLU()
        self.output_layer = nn.Linear(hidden_dim, output_dim)

    def forward(self, indices):
        embeds = self.embedding(indices)
        hidden = self.activation(self.linear(embeds))
        output = self.output_layer(hidden)
        return output

In [56]:
model = MyFirstModel(vocab_size=100, embedding_dim=16, hidden_dim=8, output_dim=2)
input_data = torch.LongTensor([[1, 2, 5, 9]])
output_data = model(input_data)
print(f"Model output shape: {output_data.shape}")

Model output shape: torch.Size([1, 4, 2])
